export type MarketplaceProduct = {
  _id: string;
  title: string;
  description: string;
  price: number;
  images: string[];
  category: string;
  subcategory?: string;
  waterType: 'Freshwater' | 'Saltwater' | 'Brackish';
  vendorId: string | { _id: string; name: string; email: string; slug?: string; logo?: string };
  tag: string;
  rating: number;
  reviewsCount?: number;
  inStock: boolean;
  approvalStatus?: 'pending' | 'approved' | 'rejected';
  scientific?: string;
  originalPrice?: number;
  discountPercentage?: number;
  perPiecePrice?: number;
  perPairPrice?: number;
  shippingType?: 'piece' | 'weight';
  shippingCharge?: number;
  shippingLotSize?: number;
  deliverNorth?: boolean;
  deliverSouth?: boolean;
  createdAt?: string;
  updatedAt?: string;
};
